title: KISEC Final Project
description: Security Assessment and Investigation Presentations
theme: jekyll-theme-minimal
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true